# Generated by Django 4.2.1 on 2023-05-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_conversationmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='applicaiton',
            new_name='application',
        ),
    ]
