# Generated by Django 4.2.1 on 2023-05-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_company_address_job_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('employed', 'Employed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.CharField(choices=[('size_1_9', '1-9'), ('size_10_49', '10-49'), ('size_50_99', '50-99'), ('size_100', '100+')], default='size_1_9', max_length=20),
        ),
    ]
